# -*- coding: utf-8 -*-
"""Iris project.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nS04NuaFDVlBMBUiT7vFj1C10Lt4s-Yy
"""

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
# %matplotlib inline

"""LOADING THE DATASET

"""

columns = ['Sepal length', 'Sepal width', 'Petal length', 'Petal width', 'Class_labels']
#Load the Data
df= pd.read_csv('iris.data', names=columns)
df.head()

"""Visualization of Dataset"""

df.describe()

#Visualize the whole dataset
sns.pairplot(df, hue='Class_labels')

"""SEPARATING INPUT COLUMNS AND THE OUTPUT COLUMN ( Data Cleaning )"""

#Separate features and target
data=df.values
X=data[:,0:4]
Y=data[:,4]
print(X)

#Split the data to trains and test dataset:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2)
print(y_train)

"""LOGISTIC REGRESSION"""

#LOGISTIC REGRESSION
from sklearn.linear_model import LogisticRegression
model_LR=LogisticRegression()
model_LR.fit(X_train,y_train)

prediction2= model_LR.predict(X_test)
# Calculate the accuracy
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test, prediction2)*100)

# A detialed classification report
from sklearn.metrics import classification_report
print(classification_report(y_test, prediction2))

X_new = np.array([[3,2,1,0.2],[4.9,2.2,3.8,1.1],[5.3,2.5,4.6,1.9]])
#Prediction of the species from the input vector
prediction = model_svc.predict(X_new)
print("Prediction of Species: {}".format(prediction))

